# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "â¯" symbol in the prompt with "ğŸš€"
[character]
success_symbol = "ğŸš€"
error_symbol = "ğŸ˜Ÿ"
vicmd_symbol = "ğŸ‘»"


[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "


[conda]
format = "[$symbol$environment](dimmed green) "


[rust]
format = "via [âš™ï¸ $version](red bold)"


[sudo]
disabled = false

